INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Parent','Restaurant Foucher','True','Mer plaindre direction sortir appel action.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Saint Roland-sur-Mer','Bistro Paris','False','Plus général police cacher.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Briand-la-Forêt','Restaurant Gros S.A.R.L.','True','Autre taire tandis que mari.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Carpentier','Café Colas','True','Police mesure jardin courant tâche former.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Sainte Thibault-les-Bains','Restaurant Perrot Normand S.A.R.L.','True','Nuit environ oublier joie falloir désir.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Blin','Bistro Ledoux S.A.','False','Agent dabord venir éclairer pointe chez huit.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Courtois','Bistro Guillon SARL','True','Secret précéder fond confier militaire.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Sainte DanielleVille','Restaurant Moreno SARL','True','Épaule capable événement.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Sainte Benjaminboeuf','Café Gomez S.A.','False','Ramasser rond recherche.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Pierre','Bistro Laporte SARL','True','Lendemain tâche réserver marche neuf prévenir.');
