INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Dupré','Restaurant Ramos Fabre S.A.','False','Sembler éprouver baisser.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Prévostboeuf','Restaurant Noël','False','En durer éclater note.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Saint Susanne-la-Forêt','Bistro Maillard','True','Former science point.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Schneiderdan','Bistro Verdier Cohen S.A.R.L.','True','Besoin moins unique étranger.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Saint Xavier','Restaurant Vaillant','True','Tendre intention mariage pain quelque combat avant.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('NeveuVille','Restaurant Roy','True','Anglais sérieux préférer rapporter.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Collin','Grill Rey Labbé et Fils','False','Importer roche chat avec noire.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Sainte Simone','Grill Coste S.A.S.','True','Auteur paysan marcher main marchand.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Colas','Restaurant Baron','True','Salut vague perte genou public éclairer.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Lemaire','Café Pons et Fils','False','Vrai portier réunir écraser.');
