INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Saint Maurice-les-Bains','Bistro Le Goff','False','Premier parent dur.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Mahe-sur-Mer','Restaurant Vincent','False','Bonheur déjà supporter remettre étendre ajouter.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Saint Virginie','Bistro Charpentier S.A.','False','Davantage regard enfant sentier suite.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Gay-sur-Gaudin','Bistro Dupuy','False','Ville angoisse traiter.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Sainte Alex-sur-Mer','Bistro Barre','True','Ressembler contraire avant appartement dabord.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Sainte Odetteboeuf','Grill Wagner Gros SA','False','Encore imposer et françois fête corps.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Brun','Grill Maurice S.A.S.','True','Certain professeur un demain donner toujours partager.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Sainte Pauline','Café Guillaume','False','Couler six transformer éviter train vide croire.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Dupuis','Café Diallo','False','Verre doucement mal.');
INSERT INTO etablissement (adresse,nom,approved,description) VALUES ('Muller','Restaurant Gaudin S.A.','True','Hors ici soir événement autre étonner devoir.');
