INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Dias','Café Le Goff','False','Jeune agiter éternel fer geste garde banc.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Saint Marthedan','Café Coste','False','Police complètement représenter renoncer expérience mon.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Pierre','Restaurant Blin','False','Raconter noire installer devant précis sien.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('ReynaudBourg','Restaurant Simon S.A.S.','True','Blanc peu distinguer esprit.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Saint Louis','Café Laurent Diallo S.A.','False','Étoile connaissance ordre charge assister.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Lemaître-la-Forêt','Grill Blanchet S.A.R.L.','False','Parfois parmi désirer mauvais.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Costa-les-Bains','Bistro Hardy','False','Miser immobile vieil soin dautres coup.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Klein','Grill Lecomte','True','Absolument blanc particulier.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Daniel-sur-Dufour','Restaurant Samson','False','Nous fort chambre cercle roche contre colline angoisse.');
INSERT INTO etablissement (adresse,nom,approuved,description) VALUES ('Toussaint','Bistro Peltier','False','Couler imposer repousser départ devant chute.');
